apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  cors-origin: {{ .Values.backend.env.CORS_ORIGIN | quote }}
  node-env: {{ .Values.backend.env.NODE_ENV | quote }}
