apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
