apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-redis
  namespace: nexus-arena
  labels:
    app: nexus-redis
    tier: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-redis
  template:
    metadata:
      labels:
        app: nexus-redis
        tier: cache
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command: ["redis-server"]
          args:
            - "--maxmemory"
            - "256mb"
            - "--maxmemory-policy"
            - "allkeys-lru"
            - "--save"
            - ""
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-redis
  namespace: nexus-arena
spec:
  type: ClusterIP
  selector:
    app: nexus-redis
  ports:
    - port: 6379
      targetPort: 6379
